import { sveltekit } from '@sveltejs/kit/vite';
import { svelteTesting } from '@testing-library/svelte/vite';
import { defineConfig } from 'vitest/config';

// SvelteKit plugin gives us `$lib/...` alias resolution and `.svelte` file
// compilation for tests. happy-dom is the DOM environment so Svelte
// components can mount; `resolve.conditions: ['browser']` ensures
// @testing-library/svelte v5 picks up the browser entry of svelte/internal.
// svelteTesting() wires up per-test DOM cleanup so renders don't bleed
// across test cases.
export default defineConfig({
  plugins: [sveltekit(), svelteTesting()],
  test: {
    // Cap Vitest's worker forks at half the cores. The default is one fork per
    // core (16 on the maintainer's machine), which spikes CPU/RAM/disk and
    // makes the whole system sluggish mid-run. Half keeps the suite fast while
    // leaving the machine responsive.
    maxWorkers: '50%',
    include: ['tests/**/*.test.ts'],
    environment: 'happy-dom',
    setupFiles: ['./tests/vitest.setup.ts'],
    coverage: {
      provider: 'v8',
      // `all: true` counts files the tests never import, so the denominator
      // reflects the whole app surface — an honest number, not just touched files.
      all: true,
      include: ['src/**'],
      exclude: [
        // Generated by tauri-specta ("do not edit") — must never be in the denominator.
        'src/lib/ipc/bindings.ts',
        // SvelteKit shell / root composition — covered by e2e (tests-e2e/), not units.
        // +layout.svelte is pure shell (css import + {@render children}); no logic.
        'src/routes/+layout.ts',
        'src/routes/+layout.svelte',
        'src/routes/+page.svelte',
        // Type-only and config files contribute no runtime branches.
        'src/**/*.d.ts',
        '**/*.config.*',
        // Static HTML shell — not JS, v8 can't parse it.
        'src/app.html',
      ],
      reporter: ['text-summary', 'json-summary', 'html'],
      reportsDirectory: './coverage-fe',
      // Ratchet floor — set just under the measured baseline so the gate is
      // real but doesn't spuriously fail. Raise these as coverage phases land.
      // Measured baseline 2026-05-30: lines 72.4, statements 75.2,
      // functions 69.9, branches 56.7. Floors sit ~2pt under baseline.
      thresholds: {
        lines: 70,
        statements: 73,
        functions: 67,
        branches: 54,
      },
    },
  },
  resolve: {
    conditions: ['browser'],
  },
});
