// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<Greeting>("greet", { name }),
	/**  Return the most recent network activity entries (up to 200). */
	networkActivity: () => __TAURI_INVOKE<AuditEntry[]>("network_activity"),
	/**
	 *  Audit entries whose host is NOT on the documented allowlist
	 *  (per `docs/PRINCIPLES.md` Part A item #2). UI shows a red banner
	 *  in the Network popover when this returns non-empty.
	 */
	networkAuditViolations: () => __TAURI_INVOKE<AuditEntry[]>("network_audit_violations"),
	/**  List all stored accounts. */
	listAccounts: () => typedError<Account[], Error>(__TAURI_INVOKE("list_accounts")),
	/**  Currently active account, or None if no account is set. */
	getActiveAccount: () => typedError<Account | null, Error>(__TAURI_INVOKE("get_active_account")),
	/**  Set the active account by id. Errors AccountNotSet if id is unknown. */
	setActiveAccount: (id: string) => typedError<null, Error>(__TAURI_INVOKE("set_active_account", { id })),
	/**
	 *  Remove an account. If it was active, the next account becomes active;
	 *  if none remain, active_id becomes None.
	 */
	removeAccount: (id: string) => typedError<null, Error>(__TAURI_INVOKE("remove_account", { id })),
	/**  Add an offline account. Idempotent — same name produces same UUID. */
	addOfflineAccount: (name: string) => typedError<Account, Error>(__TAURI_INVOKE("add_offline_account", { name })),
	/**
	 *  Fetch the Mojang version manifest. Cached for 5 minutes — repeated
	 *  calls within that window are zero-network.
	 */
	listVersions: () => typedError<VersionEntry[], Error>(__TAURI_INVOKE("list_versions")),
	/**
	 *  Install a Minecraft version: downloads the per-version JSON,
	 *  libraries, assets, and client.jar. Emits `installProgress` events
	 *  throughout. Idempotent — files already present with matching SHA-1
	 *  are skipped.
	 */
	installVersion: (versionId: string) => typedError<null, Error>(__TAURI_INVOKE("install_version", { versionId })),
	/**
	 *  Install (idempotently) and then launch the given Minecraft version.
	 *  Emits `installProgress` during install and `processSpawned` /
	 *  `processExited` around the run.
	 */
	installAndLaunch: (versionId: string) => typedError<number, Error>(__TAURI_INVOKE("install_and_launch", { versionId })),
	/**  Kill the running Minecraft process if any. Idempotent. */
	stopMinecraft: () => typedError<null, Error>(__TAURI_INVOKE("stop_minecraft")),
	/**
	 *  List every log file under the default instance's three documented
	 *  roots. Sorted by mtime descending.
	 */
	listLogFiles: () => typedError<LogFileMeta[], Error>(__TAURI_INVOKE("list_log_files")),
	/**
	 *  Read up to `max_bytes` of a log file. `max_bytes` is clamped to
	 *  `[64 KB, 100 MB]`; `0` becomes the 5 MB default. `path` must be
	 *  under one of the three allowed log roots — anything else is
	 *  rejected with `Error::Io`.
	 */
	readLogFile: (path: string, maxBytes: number | null) => typedError<string, Error>(__TAURI_INVOKE("read_log_file", { path, maxBytes })),
	/**
	 *  Newest crash report (if any). Used by the UI to show a banner on
	 *  non-zero MC exit.
	 */
	latestCrash: () => typedError<{
	path: string,
	/**
	 *  First ~500 chars of the crash report — enough to show the
	 *  stack-trace head in a banner without loading the full file.
	 */
	preview: string,
} | null, Error>(__TAURI_INVOKE("latest_crash")),
	/**
	 *  Ensure the default instance's `mods/` directory exists, then open
	 *  it in the OS file manager (Explorer on Windows). Idempotent —
	 *  safe to click repeatedly. Vanilla MC does not load mods; the UI
	 *  carries a caveat below the button.
	 */
	openModsFolder: () => typedError<null, Error>(__TAURI_INVOKE("open_mods_folder")),
	/**
	 *  List Fabric loader versions compatible with `mc_id`. Sorted
	 *  newest-first by build. Empty list → `Error::LoaderUnavailable`.
	 *  Cached 5 minutes per `mc_id`.
	 */
	listFabricLoaders: (mcId: string) => typedError<LoaderVersion[], Error>(__TAURI_INVOKE("list_fabric_loaders", { mcId })),
	/**
	 *  List Quilt loader versions compatible with `mc_id`. Same semantics
	 *  as `list_fabric_loaders`. Stability is inferred from the version
	 *  string (Quilt meta does not expose a `stable` flag).
	 */
	listQuiltLoaders: (mcId: string) => typedError<LoaderVersion[], Error>(__TAURI_INVOKE("list_quilt_loaders", { mcId })),
};

/** Events */
export const events = {
	downloadProgress: makeEvent<DownloadProgress>("download-progress"),
	installProgress: makeEvent<InstallProgress>("install-progress"),
	processExited: makeEvent<ProcessExited>("process-exited"),
	processSpawned: makeEvent<ProcessSpawned>("process-spawned"),
};

/* Types */
export type Account = {
	/**  Local UUID v4. */
	id: string,
	/**  Display name (MC username). */
	name: string,
	/**  MC UUID, canonical hyphenated form. */
	uuid: string,
	/**  Unix seconds. `None` for offline (never expires). */
	expires_at: number | null,
};

export type AuditEntry = {
	/**
	 *  Milliseconds since Unix epoch, as `f64` so JavaScript's `number`
	 *  type can round-trip it without precision loss (`Date.now()`
	 *  returns f64-compatible values too). UI formats with `new Date(ts)`.
	 */
	ts: number | null,
	method: string,
	url: string,
	/**  Module that initiated the call (`"versions"`, `"jre"`, etc.). */
	initiator: string,
	/**
	 *  Bytes transferred. `None` if the call is in progress or failed
	 *  before any body was read.
	 */
	bytes: number | null,
	/**
	 *  HTTP status code if the response was received, else `None`
	 *  (network error before status).
	 */
	status: number | null,
};

export type CrashReport = {
	path: string,
	/**
	 *  First ~500 chars of the crash report — enough to show the
	 *  stack-trace head in a banner without loading the full file.
	 */
	preview: string,
};

/**
 *  Progress event emitted during a download. The UI subscribes via
 *  `listen<DownloadProgress>("download:progress", ...)`.
 */
export type DownloadProgress = {
	url: string,
	/**
	 *  Bytes downloaded so far. `f64` for JS number compatibility (the
	 *  2^53 safe-integer range holds files up to ~9 petabytes).
	 */
	bytes_done: number | null,
	/**  `None` if the server did not send `Content-Length`. */
	bytes_total: number | null,
};

export type Error = { kind: "network"; url: string; details: string } | { kind: "hash_mismatch"; path: string; expected: string; got: string } | { kind: "java_spawn"; details: string } | { kind: "already_running" } | { kind: "account_not_set" } | { kind: "unknown_version"; id: string } | { kind: "loader_unavailable"; loader: string; mc_version: string } | { kind: "unsupported_platform"; os: string; arch: string } | { kind: "io"; path: string; details: string };

export type Greeting = {
	message: string,
};

export type InstallPhase = "manifest" | "jre" | "libraries" | "assets" | "client" | "complete";

export type InstallProgress = {
	version_id: string,
	phase: InstallPhase,
	files_done: number,
	files_total: number,
	/**  Cumulative bytes within the current phase. */
	bytes_done: number | null,
};

export type LoaderVersion = {
	version: string,
	stable: boolean,
	build: number,
};

export type LogFileMeta = {
	path: string,
	name: string,
	source: LogSource,
	/**  f64 because specta-typescript 0.0.12 forbids u64. */
	size_bytes: number | null,
	modified_unix_ms: number | null,
};

export type LogSource = "game" | "crash" | "launcher";

export type ProcessExited = {
	version_id: string,
	/**
	 *  Process exit code. `-1` when the process was terminated by a
	 *  signal (no code available from the OS).
	 */
	code: number,
	/**  Absolute path to the launch log file for this run. */
	log_path: string,
};

export type ProcessSpawned = {
	version_id: string,
	pid: number,
};

/**
 *  What the UI sees per entry. We strip the cryptographic and
 *  compliance fields the launcher core needs but the UI doesn't.
 */
export type VersionEntry = {
	id: string,
	version_type: VersionType,
	/**  ISO-8601 string from Mojang, e.g. "2023-12-07T12:00:00+00:00". */
	release_date: string,
	/**
	 *  URL to the per-version JSON. Stored so slice 4 doesn't have to
	 *  re-fetch the manifest to know where to install from.
	 */
	url: string,
};

export type VersionType = "release" | "snapshot" | "old_alpha" | "old_beta";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

