// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<Greeting>("greet", { name }),
	/**  Return the most recent network activity entries (up to 200). */
	networkActivity: () => __TAURI_INVOKE<AuditEntry[]>("network_activity"),
};

/** Events */
export const events = {
	downloadProgress: makeEvent<DownloadProgress>("download-progress"),
};

/* Types */
export type AuditEntry = {
	/**
	 *  Milliseconds since Unix epoch, as `f64` so JavaScript's `number`
	 *  type can round-trip it without precision loss (`Date.now()`
	 *  returns f64-compatible values too). UI formats with `new Date(ts)`.
	 */
	ts: number | null,
	method: string,
	url: string,
	/**  Module that initiated the call (`"versions"`, `"jre"`, etc.). */
	initiator: string,
	/**
	 *  Bytes transferred. `None` if the call is in progress or failed
	 *  before any body was read.
	 */
	bytes: number | null,
	/**
	 *  HTTP status code if the response was received, else `None`
	 *  (network error before status).
	 */
	status: number | null,
};

/**
 *  Progress event emitted during a download. The UI subscribes via
 *  `listen<DownloadProgress>("download:progress", ...)`.
 */
export type DownloadProgress = {
	url: string,
	/**
	 *  Bytes downloaded so far. `f64` for JS number compatibility (the
	 *  2^53 safe-integer range holds files up to ~9 petabytes).
	 */
	bytes_done: number | null,
	/**  `None` if the server did not send `Content-Length`. */
	bytes_total: number | null,
};

export type Greeting = {
	message: string,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

