// GENERATED by tools/gen-i18n-keys.mjs — do not edit by hand.
// Run `pnpm i18n:keys` after changing en.json.
export type TranslationKey =
  | 'common.cancel'
  | 'common.close'
  | 'common.save'
  | 'settings.general.appearance.language'
  | 'settings.general.appearance.languageSystem'
  | 'settings.general.appearance.title';
