//! Microsoft OAuth — PKCE, authorize URL, loopback listener,
//! authorization-code → MS-token exchange.
//!
//! The flow is intentionally split:
//! - `Pkce`, `build_authorize_url`, `parse_callback_request_line`
//!   are pure functions (unit-tested).
//! - `run_loopback_listener` and `exchange_code_for_token` do real I/O
//!   (integration-tested in Task 11 + 19).
//!
//! `CLIENT_ID` is a public Azure application id — desktop OAuth uses
//! PKCE, no client secret. Replace the placeholder before manual e2e.

use crate::error::{Error, Result};
use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
use rand::RngCore;
use sha2::{Digest, Sha256};
use std::time::Duration;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpListener;

/// Azure-issued public OAuth client_id (PKCE, no secret). The value is
/// public by design — every Mojang/Microsoft auth desktop launcher (Prism,
/// HMCL, Modrinth Launcher, the official MS launcher) commits theirs in
/// source. Tied to the FTlauncher app registration in the maintainer's
/// Entra tenant; rotating it requires re-registering at portal.azure.com.
pub const CLIENT_ID: &str = "f60b30f7-64cb-4d36-bc99-d55c40121603";

const MS_AUTHORIZE_URL: &str = "https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize";
pub const MS_TOKEN_URL: &str = "https://login.microsoftonline.com/consumers/oauth2/v2.0/token";
const OAUTH_SCOPES: &str = "XboxLive.signin offline_access";

/// PKCE verifier/challenge pair (RFC 7636).
pub struct Pkce {
    pub verifier: String,
    pub challenge: String,
}

impl Pkce {
    pub fn new() -> Self {
        let mut buf = [0u8; 64];
        rand::thread_rng().fill_bytes(&mut buf);
        let verifier = URL_SAFE_NO_PAD.encode(buf);
        let mut hasher = Sha256::new();
        hasher.update(verifier.as_bytes());
        let challenge = URL_SAFE_NO_PAD.encode(hasher.finalize());
        Self {
            verifier,
            challenge,
        }
    }
}

/// Build the URL the user opens in their browser. `state` is generated by
/// the caller and validated on callback.
pub fn build_authorize_url(redirect_uri: &str, challenge: &str, state: &str) -> String {
    let mut url = String::from(MS_AUTHORIZE_URL);
    url.push_str("?client_id=");
    url.push_str(CLIENT_ID);
    url.push_str("&response_type=code");
    url.push_str("&redirect_uri=");
    url.push_str(&urlencoding::encode(redirect_uri));
    url.push_str("&scope=");
    url.push_str(&urlencoding::encode(OAUTH_SCOPES));
    url.push_str("&code_challenge=");
    url.push_str(challenge);
    url.push_str("&code_challenge_method=S256");
    url.push_str("&state=");
    url.push_str(state);
    url
}

/// Result of parsing the first request line of the loopback HTTP request.
#[derive(Debug, PartialEq, Eq)]
pub enum CallbackOutcome {
    Code { code: String, state: String },
    OAuthError { description: String },
    UnrelatedPath,
}

/// Parse e.g. `GET /oauth/callback?code=ABC&state=XYZ HTTP/1.1`. We do not
/// implement a real HTTP parser — just split the request line and the query
/// string. The loopback listener writes the entire response in one go.
pub fn parse_callback_request_line(line: &str) -> CallbackOutcome {
    let parts: Vec<&str> = line.split_whitespace().collect();
    if parts.len() < 2 || parts[0] != "GET" {
        return CallbackOutcome::UnrelatedPath;
    }
    let path = parts[1];
    if !path.starts_with("/oauth/callback") {
        return CallbackOutcome::UnrelatedPath;
    }
    let Some(query) = path.split_once('?').map(|(_, q)| q) else {
        return CallbackOutcome::UnrelatedPath;
    };
    let mut code = None;
    let mut state = None;
    let mut err = None;
    let mut err_desc = None;
    for kv in query.split('&') {
        let Some((k, v)) = kv.split_once('=') else {
            continue;
        };
        let decoded = urlencoding::decode(v)
            .map(|c| c.into_owned())
            .unwrap_or_else(|_| v.to_string());
        match k {
            "code" => code = Some(decoded),
            "state" => state = Some(decoded),
            "error" => err = Some(decoded),
            "error_description" => err_desc = Some(decoded),
            _ => {}
        }
    }
    if let Some(_e) = err {
        return CallbackOutcome::OAuthError {
            description: err_desc.unwrap_or_else(|| "unknown".into()),
        };
    }
    match (code, state) {
        (Some(c), Some(s)) => CallbackOutcome::Code { code: c, state: s },
        _ => CallbackOutcome::UnrelatedPath,
    }
}

/// MS-token POST response.
#[derive(Debug, serde::Deserialize)]
pub struct MsTokenResponse {
    pub access_token: String,
    pub refresh_token: String,
    pub expires_in: u64,
}

/// Exchange the authorization code for an MS access_token + refresh_token.
/// Called after the listener captures the `code`.
pub async fn exchange_code_for_token(
    code: &str,
    code_verifier: &str,
    redirect_uri: &str,
    token_url: &str,
) -> Result<MsTokenResponse> {
    let body = format!(
        "client_id={}&grant_type=authorization_code&code={}&code_verifier={}&redirect_uri={}",
        CLIENT_ID,
        urlencoding::encode(code),
        urlencoding::encode(code_verifier),
        urlencoding::encode(redirect_uri),
    );
    crate::network::allowlist::check_url_allowed(token_url, "microsoft_auth")?;
    let resp = crate::network::http()
        .post(token_url)
        .header("Content-Type", "application/x-www-form-urlencoded")
        .body(body)
        .send()
        .await
        .map_err(|e| Error::network(token_url, e))?;
    if !resp.status().is_success() {
        let status = resp.status();
        let text = resp.text().await.unwrap_or_default();
        return Err(Error::AuthFailed {
            stage: "microsoft_token".into(),
            details: format!("HTTP {status}: {text}"),
        });
    }
    resp.json::<MsTokenResponse>()
        .await
        .map_err(|e| Error::AuthFailed {
            stage: "microsoft_token".into(),
            details: format!("parse: {e}"),
        })
}

const LOOPBACK_RESPONSE_BODY: &str =
    "<!DOCTYPE html><html><body><h2>You can close this tab.</h2></body></html>";

/// Bind a tokio TcpListener on 127.0.0.1:0 and return the listener and the
/// concrete `redirect_uri` (with the OS-assigned port) the caller passes to
/// `build_authorize_url`.
pub async fn bind_listener() -> Result<(TcpListener, String)> {
    let listener = TcpListener::bind("127.0.0.1:0")
        .await
        .map_err(|e| Error::io("<loopback>", format!("bind: {e}")))?;
    let port = listener
        .local_addr()
        .map_err(|e| Error::io("<loopback>", format!("local_addr: {e}")))?
        .port();
    let redirect_uri = format!("http://127.0.0.1:{port}/oauth/callback");
    Ok((listener, redirect_uri))
}

/// Accept one connection, read until \r\n\r\n (or 4 KiB max), parse the
/// first request line, write a minimal HTML response. Returns the
/// `CallbackOutcome`. Times out after `timeout`.
pub async fn run_loopback_listener(
    listener: TcpListener,
    timeout: Duration,
) -> Result<CallbackOutcome> {
    let accept_fut = listener.accept();
    let (mut stream, _peer) = tokio::time::timeout(timeout, accept_fut)
        .await
        .map_err(|_| Error::AuthCancelled)?
        .map_err(|e| Error::io("<loopback>", format!("accept: {e}")))?;

    // Read until we see the end of headers, capped at 4 KiB.
    let mut buf = Vec::with_capacity(1024);
    let mut chunk = [0u8; 512];
    loop {
        if buf.len() > 4096 {
            break;
        }
        let n = stream
            .read(&mut chunk)
            .await
            .map_err(|e| Error::io("<loopback>", format!("read: {e}")))?;
        if n == 0 {
            break;
        }
        buf.extend_from_slice(&chunk[..n]);
        if buf.windows(4).any(|w| w == b"\r\n\r\n") {
            break;
        }
    }

    let head = String::from_utf8_lossy(&buf);
    let first_line = head.lines().next().unwrap_or("");
    let outcome = parse_callback_request_line(first_line);

    let response = format!(
        "HTTP/1.1 200 OK\r\nContent-Type: text/html; charset=utf-8\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",
        LOOPBACK_RESPONSE_BODY.len(),
        LOOPBACK_RESPONSE_BODY,
    );
    let _ = stream.write_all(response.as_bytes()).await;
    let _ = stream.shutdown().await;
    Ok(outcome)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pkce_pair_is_well_formed() {
        let p = Pkce::new();
        // Verifier is base64url-no-pad of 64 random bytes -> ~86 chars.
        assert!(
            p.verifier.len() >= 80,
            "verifier too short: {}",
            p.verifier.len()
        );
        // Challenge is SHA-256 of verifier -> 32 bytes -> base64url-no-pad ~43 chars.
        assert_eq!(p.challenge.len(), 43, "got {}", p.challenge.len());
        // No padding chars.
        assert!(!p.verifier.contains('='));
        assert!(!p.challenge.contains('='));
    }

    #[test]
    fn pkce_challenge_matches_sha256_of_verifier() {
        let p = Pkce::new();
        let mut hasher = Sha256::new();
        hasher.update(p.verifier.as_bytes());
        let expected = URL_SAFE_NO_PAD.encode(hasher.finalize());
        assert_eq!(p.challenge, expected);
    }

    #[test]
    fn build_authorize_url_contains_all_params() {
        let url = build_authorize_url(
            "http://127.0.0.1:12345/oauth/callback",
            "test-challenge",
            "test-state-xyz",
        );
        assert!(url.starts_with(MS_AUTHORIZE_URL));
        assert!(url.contains("response_type=code"));
        assert!(url.contains("code_challenge=test-challenge"));
        assert!(url.contains("code_challenge_method=S256"));
        assert!(url.contains("state=test-state-xyz"));
        assert!(url.contains("client_id="));
        assert!(url.contains("redirect_uri=http%3A%2F%2F127.0.0.1%3A12345%2Foauth%2Fcallback"));
        assert!(url.contains("scope=XboxLive.signin%20offline_access"));
    }

    #[test]
    fn parse_callback_happy_path() {
        let line = "GET /oauth/callback?code=ABC123&state=XYZ HTTP/1.1";
        match parse_callback_request_line(line) {
            CallbackOutcome::Code { code, state } => {
                assert_eq!(code, "ABC123");
                assert_eq!(state, "XYZ");
            }
            other => panic!("expected Code, got {other:?}"),
        }
    }

    #[test]
    fn parse_callback_with_error_param() {
        let line =
            "GET /oauth/callback?error=access_denied&error_description=user_cancelled HTTP/1.1";
        match parse_callback_request_line(line) {
            CallbackOutcome::OAuthError { description } => {
                assert_eq!(description, "user_cancelled");
            }
            other => panic!("expected OAuthError, got {other:?}"),
        }
    }

    #[test]
    fn parse_callback_unrelated_path() {
        let line = "GET /favicon.ico HTTP/1.1";
        assert_eq!(
            parse_callback_request_line(line),
            CallbackOutcome::UnrelatedPath
        );
    }

    #[test]
    fn parse_callback_missing_state() {
        let line = "GET /oauth/callback?code=ABC HTTP/1.1";
        assert_eq!(
            parse_callback_request_line(line),
            CallbackOutcome::UnrelatedPath
        );
    }

    #[test]
    fn parse_callback_post_request_rejected() {
        let line = "POST /oauth/callback?code=ABC&state=XYZ HTTP/1.1";
        assert_eq!(
            parse_callback_request_line(line),
            CallbackOutcome::UnrelatedPath
        );
    }

    #[tokio::test]
    async fn loopback_listener_captures_code_from_emulated_browser() {
        let (listener, redirect_uri) = bind_listener().await.unwrap();
        let port = redirect_uri
            .rsplit_once(':')
            .and_then(|(_, p)| p.split('/').next())
            .and_then(|p| p.parse::<u16>().ok())
            .unwrap();

        // Spawn the listener to run concurrently.
        let listener_fut =
            tokio::spawn(
                async move { run_loopback_listener(listener, Duration::from_secs(5)).await },
            );

        // Emulate the browser hitting the redirect URI.
        // tiny pause to let listener reach .accept().await.
        tokio::time::sleep(Duration::from_millis(50)).await;
        let _resp = crate::network::http()
            .get(format!(
                "http://127.0.0.1:{port}/oauth/callback?code=FAKE&state=ST"
            ))
            .send()
            .await
            .unwrap();

        let outcome = listener_fut.await.unwrap().unwrap();
        match outcome {
            CallbackOutcome::Code { code, state } => {
                assert_eq!(code, "FAKE");
                assert_eq!(state, "ST");
            }
            other => panic!("expected Code, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn loopback_listener_times_out_when_no_callback() {
        let (listener, _redirect_uri) = bind_listener().await.unwrap();
        let result = run_loopback_listener(listener, Duration::from_millis(100)).await;
        assert!(
            matches!(result, Err(Error::AuthCancelled)),
            "got {result:?}"
        );
    }
}
