//! Microsoft OAuth — PKCE, authorize URL, loopback listener,
//! authorization-code → MS-token exchange.
//!
//! The flow is intentionally split:
//! - `Pkce`, `build_authorize_url`, `parse_callback_request_line`
//!   are pure functions (unit-tested).
//! - `run_loopback_listener` and `exchange_code_for_token` do real I/O
//!   (integration-tested in Task 11 + 19).
//!
//! `CLIENT_ID` is a public Azure application id — desktop OAuth uses
//! PKCE, no client secret. Overridable at build time via the
//! `LUCERNA_MS_CLIENT_ID` env var (see the const doc below).

use crate::error::{Error, Result};
use base64::{
    engine::general_purpose::{STANDARD, URL_SAFE_NO_PAD},
    Engine as _,
};
use rand::RngCore;
use sha2::{Digest, Sha256};
use std::sync::OnceLock;
use std::time::Duration;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpListener;

/// Azure-issued public OAuth client_id (PKCE, no secret). The value is
/// public by design — every Mojang/Microsoft auth desktop launcher (Prism,
/// HMCL, Modrinth Launcher, the official MS launcher) commits theirs in
/// source. Tied to the Lucerna app registration in the maintainer's
/// Entra tenant; rotating it requires re-registering at portal.azure.com.
///
/// Overridable at build time via the `LUCERNA_MS_CLIENT_ID` env var, so a
/// fork can bake in its OWN Azure registration without editing source:
/// `LUCERNA_MS_CLIENT_ID=<your-id> pnpm tauri build`. Resolved at compile
/// time (`option_env!`), so the value is embedded in the shipped binary —
/// the end-user installer needs no env var or Azure account; users just
/// sign in with their own Microsoft account. If you DISTRIBUTE a fork,
/// register your own app and set this rather than shipping under Lucerna's
/// identity (a consumer would otherwise see "Lucerna" on the Microsoft
/// consent screen). See CONTRIBUTING.md → "Microsoft sign-in (Azure app)".
pub const CLIENT_ID: &str = match option_env!("LUCERNA_MS_CLIENT_ID") {
    Some(id) => id,
    None => "f60b30f7-64cb-4d36-bc99-d55c40121603",
};

const MS_AUTHORIZE_URL: &str = "https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize";
pub const MS_TOKEN_URL: &str = "https://login.microsoftonline.com/consumers/oauth2/v2.0/token";
const OAUTH_SCOPES: &str = "XboxLive.signin offline_access";

/// PKCE verifier/challenge pair (RFC 7636).
pub struct Pkce {
    pub verifier: String,
    pub challenge: String,
}

impl Pkce {
    pub fn new() -> Self {
        let mut buf = [0u8; 64];
        rand::thread_rng().fill_bytes(&mut buf);
        let verifier = URL_SAFE_NO_PAD.encode(buf);
        let mut hasher = Sha256::new();
        hasher.update(verifier.as_bytes());
        let challenge = URL_SAFE_NO_PAD.encode(hasher.finalize());
        Self {
            verifier,
            challenge,
        }
    }
}

/// Build the URL the user opens in their browser. `state` is generated by
/// the caller and validated on callback.
pub fn build_authorize_url(redirect_uri: &str, challenge: &str, state: &str) -> String {
    let mut url = String::from(MS_AUTHORIZE_URL);
    url.push_str("?client_id=");
    url.push_str(CLIENT_ID);
    url.push_str("&response_type=code");
    url.push_str("&redirect_uri=");
    url.push_str(&urlencoding::encode(redirect_uri));
    url.push_str("&scope=");
    url.push_str(&urlencoding::encode(OAUTH_SCOPES));
    url.push_str("&code_challenge=");
    url.push_str(challenge);
    url.push_str("&code_challenge_method=S256");
    url.push_str("&state=");
    url.push_str(state);
    // Always present the account chooser. Without this, Microsoft reuses the
    // browser's existing login session, which makes adding a *second* account
    // impossible for a user already signed into one MS account in their
    // default browser. The launcher supports N accounts, so the chooser is the
    // correct default.
    url.push_str("&prompt=select_account");
    url
}

/// Result of parsing the first request line of the loopback HTTP request.
#[derive(Debug, PartialEq, Eq)]
pub enum CallbackOutcome {
    Code { code: String, state: String },
    OAuthError { description: String },
    UnrelatedPath,
}

/// Parse e.g. `GET /oauth/callback?code=ABC&state=XYZ HTTP/1.1`. We do not
/// implement a real HTTP parser — just split the request line and the query
/// string. The loopback listener writes the entire response in one go.
pub fn parse_callback_request_line(line: &str) -> CallbackOutcome {
    let parts: Vec<&str> = line.split_whitespace().collect();
    if parts.len() < 2 || parts[0] != "GET" {
        return CallbackOutcome::UnrelatedPath;
    }
    let path = parts[1];
    if !path.starts_with("/oauth/callback") {
        return CallbackOutcome::UnrelatedPath;
    }
    let Some(query) = path.split_once('?').map(|(_, q)| q) else {
        return CallbackOutcome::UnrelatedPath;
    };
    let mut code = None;
    let mut state = None;
    let mut err = None;
    let mut err_desc = None;
    for kv in query.split('&') {
        let Some((k, v)) = kv.split_once('=') else {
            continue;
        };
        let decoded = urlencoding::decode(v)
            .map(|c| c.into_owned())
            .unwrap_or_else(|_| v.to_string());
        match k {
            "code" => code = Some(decoded),
            "state" => state = Some(decoded),
            "error" => err = Some(decoded),
            "error_description" => err_desc = Some(decoded),
            _ => {}
        }
    }
    if let Some(_e) = err {
        return CallbackOutcome::OAuthError {
            description: err_desc.unwrap_or_else(|| "unknown".into()),
        };
    }
    match (code, state) {
        (Some(c), Some(s)) => CallbackOutcome::Code { code: c, state: s },
        _ => CallbackOutcome::UnrelatedPath,
    }
}

/// MS-token POST response.
#[derive(Debug, serde::Deserialize)]
pub struct MsTokenResponse {
    pub access_token: String,
    pub refresh_token: String,
    pub expires_in: u64,
}

/// Exchange the authorization code for an MS access_token + refresh_token.
/// Called after the listener captures the `code`.
pub async fn exchange_code_for_token(
    code: &str,
    code_verifier: &str,
    redirect_uri: &str,
    token_url: &str,
) -> Result<MsTokenResponse> {
    let body = format!(
        "client_id={}&grant_type=authorization_code&code={}&code_verifier={}&redirect_uri={}",
        CLIENT_ID,
        urlencoding::encode(code),
        urlencoding::encode(code_verifier),
        urlencoding::encode(redirect_uri),
    );
    crate::network::allowlist::check_url_allowed(token_url, "microsoft_auth")?;
    let resp = crate::network::http()
        .post(token_url)
        .header("Content-Type", "application/x-www-form-urlencoded")
        .body(body)
        .send()
        .await
        .map_err(|e| Error::network(token_url, e))?;
    if !resp.status().is_success() {
        let status = resp.status();
        let text = resp.text().await.unwrap_or_default();
        return Err(Error::AuthFailed {
            stage: "microsoft_token".into(),
            details: format!("HTTP {status}: {text}"),
        });
    }
    resp.json::<MsTokenResponse>()
        .await
        .map_err(|e| Error::AuthFailed {
            stage: "microsoft_token".into(),
            details: format!("parse: {e}"),
        })
}

// The Lucerna app icon, embedded at compile time. The callback page is served
// once from a local socket with no network or file access, so the icon is
// inlined as a base64 data URI rather than referenced by URL.
const APP_ICON_PNG: &[u8] = include_bytes!("../../../icons/128x128.png");

/// `data:image/png;base64,...` URI for the app icon, built once. ASCII-only
/// (base64 alphabet + the literal prefix), keeping the page byte-length ==
/// char-length for `Content-Length`.
fn icon_data_uri() -> &'static str {
    static URI: OnceLock<String> = OnceLock::new();
    URI.get_or_init(|| format!("data:image/png;base64,{}", STANDARD.encode(APP_ICON_PNG)))
}

/// Build a self-contained callback page. The styling is fully inline (no
/// external assets — see `APP_ICON_PNG`). The page stays English by design,
/// like other Rust-served user-facing prose (e.g. log diagnoses). `heading`
/// and `message` are fixed, caller-controlled literals — no user input is
/// interpolated, so there is no injection surface.
fn build_callback_page(heading: &str, message: &str) -> String {
    format!(
        r#"<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Lucerna</title><style>html,body{{height:100%;margin:0}}body{{display:flex;align-items:center;justify-content:center;background:#161719;color:#e8e8ea;font-family:'Segoe UI',system-ui,sans-serif}}main{{text-align:center;padding:2rem;max-width:30rem}}.logo{{width:72px;height:72px;border-radius:16px;margin-bottom:1rem}}.brand{{font-weight:700;font-size:1.1rem;letter-spacing:.04em;color:#9b8cff;margin-bottom:1.5rem}}h1{{font-size:1.4rem;margin:0 0 .5rem}}p{{margin:0;color:#a0a0a8;line-height:1.5}}</style></head><body><main><img class="logo" width="72" height="72" alt="Lucerna" src="{icon}"><div class="brand">Lucerna</div><h1>{heading}</h1><p>{message}</p></main></body></html>"#,
        icon = icon_data_uri(),
    )
}

/// The success page, built once.
fn loopback_body_success() -> &'static str {
    static BODY: OnceLock<String> = OnceLock::new();
    // Neutral wording on purpose: this page is written the instant the OAuth
    // code arrives, *before* the launcher verifies the Minecraft profile /
    // ownership. The definitive result (including the "no Minecraft" case) is
    // shown back in Lucerna, so the page must not claim the sign-in succeeded.
    BODY.get_or_init(|| {
        build_callback_page(
            "Almost there",
            "Return to Lucerna to finish signing in. You can close this tab.",
        )
    })
}

/// The OAuth-error page, built once.
fn loopback_body_error() -> &'static str {
    static BODY: OnceLock<String> = OnceLock::new();
    BODY.get_or_init(|| {
        build_callback_page(
            "Sign-in didn't complete",
            "You can close this tab, return to Lucerna, and try signing in again.",
        )
    })
}

/// Pick the callback-page body based on the parsed outcome: a dedicated error
/// page when the provider returned an OAuth error, otherwise the success page.
fn loopback_response_body(outcome: &CallbackOutcome) -> &'static str {
    match outcome {
        CallbackOutcome::OAuthError { .. } => loopback_body_error(),
        CallbackOutcome::Code { .. } | CallbackOutcome::UnrelatedPath => loopback_body_success(),
    }
}

/// Bind a tokio TcpListener on 127.0.0.1:0 and return the listener and the
/// concrete `redirect_uri` (with the OS-assigned port) the caller passes to
/// `build_authorize_url`.
pub async fn bind_listener() -> Result<(TcpListener, String)> {
    let listener = TcpListener::bind("127.0.0.1:0")
        .await
        .map_err(|e| Error::io("<loopback>", format!("bind: {e}")))?;
    let port = listener
        .local_addr()
        .map_err(|e| Error::io("<loopback>", format!("local_addr: {e}")))?
        .port();
    let redirect_uri = format!("http://127.0.0.1:{port}/oauth/callback");
    Ok((listener, redirect_uri))
}

/// Accept connections until a real OAuth callback arrives, then parse the
/// first request line and write a minimal HTML response. Returns the
/// `CallbackOutcome`. Times out (overall) after `timeout`.
///
/// Browsers routinely open speculative "preconnect" sockets to the redirect
/// host and either send nothing or request an unrelated path (favicon, etc.)
/// before the real `/oauth/callback` request. Handling only the first accepted
/// socket would abort sign-in on one of those noise connections. Instead we
/// loop: an empty read or an `UnrelatedPath` gets a 404 and we go back to
/// accept the next connection, subtracting elapsed time from the budget. Only
/// a real `Code` / `OAuthError`, or the overall deadline, ends the loop.
pub async fn run_loopback_listener(
    listener: TcpListener,
    timeout: Duration,
) -> Result<CallbackOutcome> {
    let deadline = tokio::time::Instant::now() + timeout;
    loop {
        let remaining = deadline.saturating_duration_since(tokio::time::Instant::now());
        if remaining.is_zero() {
            return Err(Error::AuthCancelled);
        }
        let (mut stream, _peer) = tokio::time::timeout(remaining, listener.accept())
            .await
            .map_err(|_| Error::AuthCancelled)?
            .map_err(|e| Error::io("<loopback>", format!("accept: {e}")))?;

        // Read until we see the end of headers, capped at 4 KiB.
        let mut buf = Vec::with_capacity(1024);
        let mut chunk = [0u8; 512];
        loop {
            if buf.len() > 4096 {
                break;
            }
            let n = stream
                .read(&mut chunk)
                .await
                .map_err(|e| Error::io("<loopback>", format!("read: {e}")))?;
            if n == 0 {
                break;
            }
            buf.extend_from_slice(&chunk[..n]);
            if buf.windows(4).any(|w| w == b"\r\n\r\n") {
                break;
            }
        }

        let head = String::from_utf8_lossy(&buf);
        let first_line = head.lines().next().unwrap_or("");
        let outcome = parse_callback_request_line(first_line);

        // Noise connection (browser preconnect / favicon / empty read): answer
        // 404 so the socket closes cleanly, then loop back to accept the real
        // callback within the remaining budget.
        if matches!(outcome, CallbackOutcome::UnrelatedPath) {
            let _ = stream.write_all(not_found_response().as_bytes()).await;
            let _ = stream.shutdown().await;
            continue;
        }

        let body = loopback_response_body(&outcome);
        let response = format!(
            "HTTP/1.1 200 OK\r\nContent-Type: text/html; charset=utf-8\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",
            body.len(),
            body,
        );
        let _ = stream.write_all(response.as_bytes()).await;
        let _ = stream.shutdown().await;
        return Ok(outcome);
    }
}

/// Minimal 404 response for noise connections (browser preconnect sockets,
/// favicon probes) that hit the loopback before the real OAuth callback.
fn not_found_response() -> &'static str {
    "HTTP/1.1 404 Not Found\r\nContent-Length: 0\r\nConnection: close\r\n\r\n"
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pkce_pair_is_well_formed() {
        let p = Pkce::new();
        // Verifier is base64url-no-pad of 64 random bytes -> ~86 chars.
        assert!(
            p.verifier.len() >= 80,
            "verifier too short: {}",
            p.verifier.len()
        );
        // Challenge is SHA-256 of verifier -> 32 bytes -> base64url-no-pad ~43 chars.
        assert_eq!(p.challenge.len(), 43, "got {}", p.challenge.len());
        // No padding chars.
        assert!(!p.verifier.contains('='));
        assert!(!p.challenge.contains('='));
    }

    #[test]
    fn pkce_challenge_matches_sha256_of_verifier() {
        let p = Pkce::new();
        let mut hasher = Sha256::new();
        hasher.update(p.verifier.as_bytes());
        let expected = URL_SAFE_NO_PAD.encode(hasher.finalize());
        assert_eq!(p.challenge, expected);
    }

    #[test]
    fn build_authorize_url_contains_all_params() {
        let url = build_authorize_url(
            "http://127.0.0.1:12345/oauth/callback",
            "test-challenge",
            "test-state-xyz",
        );
        assert!(url.starts_with(MS_AUTHORIZE_URL));
        assert!(url.contains("response_type=code"));
        assert!(url.contains("code_challenge=test-challenge"));
        assert!(url.contains("code_challenge_method=S256"));
        assert!(url.contains("state=test-state-xyz"));
        assert!(url.contains("client_id="));
        assert!(url.contains("redirect_uri=http%3A%2F%2F127.0.0.1%3A12345%2Foauth%2Fcallback"));
        assert!(url.contains("scope=XboxLive.signin%20offline_access"));
        // Force the account chooser every time so a user can sign into a
        // *different* Microsoft account instead of silently reusing the
        // browser's existing session.
        assert!(url.contains("prompt=select_account"));
    }

    #[test]
    fn parse_callback_happy_path() {
        let line = "GET /oauth/callback?code=ABC123&state=XYZ HTTP/1.1";
        match parse_callback_request_line(line) {
            CallbackOutcome::Code { code, state } => {
                assert_eq!(code, "ABC123");
                assert_eq!(state, "XYZ");
            }
            other => panic!("expected Code, got {other:?}"),
        }
    }

    #[test]
    fn parse_callback_with_error_param() {
        let line =
            "GET /oauth/callback?error=access_denied&error_description=user_cancelled HTTP/1.1";
        match parse_callback_request_line(line) {
            CallbackOutcome::OAuthError { description } => {
                assert_eq!(description, "user_cancelled");
            }
            other => panic!("expected OAuthError, got {other:?}"),
        }
    }

    #[test]
    fn parse_callback_unrelated_path() {
        let line = "GET /favicon.ico HTTP/1.1";
        assert_eq!(
            parse_callback_request_line(line),
            CallbackOutcome::UnrelatedPath
        );
    }

    #[test]
    fn parse_callback_missing_state() {
        let line = "GET /oauth/callback?code=ABC HTTP/1.1";
        assert_eq!(
            parse_callback_request_line(line),
            CallbackOutcome::UnrelatedPath
        );
    }

    #[test]
    fn parse_callback_post_request_rejected() {
        let line = "POST /oauth/callback?code=ABC&state=XYZ HTTP/1.1";
        assert_eq!(
            parse_callback_request_line(line),
            CallbackOutcome::UnrelatedPath
        );
    }

    #[tokio::test]
    async fn loopback_listener_captures_code_from_emulated_browser() {
        let (listener, redirect_uri) = bind_listener().await.unwrap();
        let port = redirect_uri
            .rsplit_once(':')
            .and_then(|(_, p)| p.split('/').next())
            .and_then(|p| p.parse::<u16>().ok())
            .unwrap();

        // Spawn the listener to run concurrently.
        let listener_fut =
            tokio::spawn(
                async move { run_loopback_listener(listener, Duration::from_secs(5)).await },
            );

        // Emulate the browser hitting the redirect URI.
        // tiny pause to let listener reach .accept().await.
        tokio::time::sleep(Duration::from_millis(50)).await;
        let _resp = crate::network::http()
            .get(format!(
                "http://127.0.0.1:{port}/oauth/callback?code=FAKE&state=ST"
            ))
            .send()
            .await
            .unwrap();

        let outcome = listener_fut.await.unwrap().unwrap();
        match outcome {
            CallbackOutcome::Code { code, state } => {
                assert_eq!(code, "FAKE");
                assert_eq!(state, "ST");
            }
            other => panic!("expected Code, got {other:?}"),
        }
    }

    #[test]
    fn loopback_body_success_for_code_and_unrelated() {
        let code = CallbackOutcome::Code {
            code: "c".into(),
            state: "s".into(),
        };
        assert_eq!(loopback_response_body(&code), loopback_body_success());
        assert_eq!(
            loopback_response_body(&CallbackOutcome::UnrelatedPath),
            loopback_body_success()
        );
    }

    #[test]
    fn loopback_body_error_for_oauth_error() {
        let err = CallbackOutcome::OAuthError {
            description: "access_denied".into(),
        };
        assert_eq!(loopback_response_body(&err), loopback_body_error());
    }

    #[test]
    fn loopback_bodies_are_branded_html_and_ascii() {
        for body in [loopback_body_success(), loopback_body_error()] {
            assert!(body.starts_with("<!DOCTYPE html>"));
            assert!(body.contains("Lucerna"));
            // The embedded app icon is inlined as a base64 data URI (no network
            // / file access on the callback socket).
            assert!(body.contains("src=\"data:image/png;base64,"));
            // ASCII-only keeps Content-Length (byte length) == character length.
            assert!(body.is_ascii(), "callback body must be ASCII");
        }
        // The two pages say different things.
        assert_ne!(loopback_body_success(), loopback_body_error());
    }

    #[tokio::test]
    async fn loopback_listener_skips_noise_then_captures_code() {
        let (listener, redirect_uri) = bind_listener().await.unwrap();
        let port = redirect_uri
            .rsplit_once(':')
            .and_then(|(_, p)| p.split('/').next())
            .and_then(|p| p.parse::<u16>().ok())
            .unwrap();

        let listener_fut =
            tokio::spawn(
                async move { run_loopback_listener(listener, Duration::from_secs(5)).await },
            );

        // First: a noise request to an unrelated path (browser favicon probe).
        // The listener must 404 it and keep waiting.
        tokio::time::sleep(Duration::from_millis(50)).await;
        let _noise = crate::network::http()
            .get(format!("http://127.0.0.1:{port}/favicon.ico"))
            .send()
            .await
            .unwrap();

        // Then: the real OAuth callback.
        let _resp = crate::network::http()
            .get(format!(
                "http://127.0.0.1:{port}/oauth/callback?code=REAL&state=ST"
            ))
            .send()
            .await
            .unwrap();

        let outcome = listener_fut.await.unwrap().unwrap();
        match outcome {
            CallbackOutcome::Code { code, state } => {
                assert_eq!(code, "REAL");
                assert_eq!(state, "ST");
            }
            other => panic!("expected Code after noise, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn loopback_listener_times_out_when_no_callback() {
        let (listener, _redirect_uri) = bind_listener().await.unwrap();
        let result = run_loopback_listener(listener, Duration::from_millis(100)).await;
        assert!(
            matches!(result, Err(Error::AuthCancelled)),
            "got {result:?}"
        );
    }
}
